# Generated by Django 4.1.1 on 2022-10-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("autor", models.CharField(max_length=100)),
                ("titulo", models.CharField(max_length=100)),
                ("subtitulo", models.CharField(max_length=100)),
                ("cuerpo", models.CharField(max_length=100)),
                ("fecha", models.DateField(null=True)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="avatares"),
                ),
            ],
        ),
    ]
